name:                commandr
version:             0.1.0.0
github:              "cjdelee/commandr"
license:             BSD3
author:              "Connor DeLee"
maintainer:          "example@example.com"
copyright:           "2022 Connor DeLee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/commandr#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk == 3.0.38
- gi-gtk-hs
- haskell-gi-base
- directory
- process
- unix

library:
  source-dirs: src

executables:
  commandr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - commandr

tests:
  commandr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - commandr
